import { Link } from 'react-router'
import LegalPage, { SupportEmail } from '../components/LegalPage'

export default function PrintPolicy() {
    return <LegalPage title="Print Orders & Returns">
        <section><h2>Who handles your order</h2><p>Ian Truong is the seller of the photographs. The website integrates Fotomoto, a Bay Photo service that coordinates checkout, print production, shipping, and order support. Payment options are identified in checkout. I remain responsible for addressing order problems and refunds as the seller. Contact <SupportEmail subject="Print order support" /> or use <a href="https://support.fotomoto.com/hc/en-us/requests/new">Fotomoto support</a>. Include your order number if available; do not email payment-card details.</p></section>
        <section><h2>Before paying</h2><p>Review the selected photograph, product, size, crop, quantity, delivery address, shipping option, and total including any shipping charges and applicable taxes in checkout. Buying a print does not transfer copyright; you may use my photographs under the broad permission in <Link to="/terms">Terms & Photo Use</Link>, including commercial use without credit. Available products and destination options are those offered by the store at checkout. International deliveries may incur destination customs duties or import charges in addition to the checkout total.</p><p>See <a href="https://www.fotomoto.com/help/terms">Fotomoto’s terms</a>, <a href="https://www.fotomoto.com/help/privacy">privacy policy</a>, and <a href="https://support.fotomoto.com/hc/en-us/articles/41715076303379-Fotomoto-Refund-Policy">refund-support policy</a>. If the amount, availability, or terms are unclear, contact me before placing the order.</p></section>
        <section><h2>Production and shipping</h2><p>After you order, I supply the print-ready photograph to Fotomoto for production. Production and transit are separate stages; the shipping service’s transit estimate does not necessarily include production time. Refer to your checkout and confirmation for the estimate applicable to your order.</p><p>If no shipment time is stated, the order must be handled under the applicable default shipping rules. If we cannot meet a promised shipment time, or the applicable default period, you will receive the required delay notice and an opportunity to agree to the delay or cancel for a refund. Contact support if your order is delayed or you have not received an update.</p></section>
        <section><h2>Returns, damaged items, and cancellations</h2><p>Contact me promptly about a damaged, incorrect, missing, or otherwise problematic order. If possible, keep the packaging and include photographs of damage or an incorrect item so the issue can be investigated. Fotomoto can help coordinate an investigation, but its current support policy assigns refund responsibility to the seller.</p><p>For a change-of-mind return, contact me before sending anything back. Requests are reviewed individually; there is no blanket change-of-mind return guarantee on this site. Any approved return’s deadline, return address, shipping responsibility, and refund amount will be confirmed in writing. Any more favorable terms expressly offered with your order will be honored.</p><p>For cancellation or a change to an order, contact me as soon as possible. Available options depend on whether production or shipment has started; a voluntary cancellation is confirmed when you receive confirmation. This does not limit any cancellation right or remedy required by law for defective, incorrect, delayed, or undelivered goods, including any required shipping refund.</p></section>
        <section><h2>Need help with checkout?</h2><p>If the print interface is inaccessible or fails, email <SupportEmail subject="Help ordering a print" /> with the photograph and product you are interested in. I can help identify the options and arrange an accessible next step. Do not include payment information in your message.</p></section>
    </LegalPage>
}
