import { Link } from 'react-router'
import LegalPage, { SupportEmail } from '../components/LegalPage'

export default function Terms() {
    return <LegalPage title="Terms & Photo Use">
        <section><h2>About this website</h2><p>Ian Truong, an individual photographer based in Oregon, operates Ian Truong Photography. These terms describe website access and the photo-use permission offered here. A separate written permission or agreement for particular photographs takes precedence for those photographs. Contact <SupportEmail /> with questions.</p></section>
        <section><h2>Personal use without credit; commercial use with credit</h2><p>For photographs that I own and make available to you through this site, I grant you a worldwide, nonexclusive, royalty-free permission to download, copy, edit, print, publish, share, distribute, sublicense, and sell them for any lawful purpose, subject to the credit requirements below. You do not need to request separate permission.</p><p><strong>Personal use:</strong> You may download, edit, print, and share photographs for your own noncommercial use without credit.</p><p><strong>Commercial use:</strong> You must provide clear, readable credit to Ian Truong, such as “Photo: Ian Truong,” alongside the photograph or in the accompanying publication, product, or project credits. Commercial use includes advertising, business promotion, products for sale, and commercial licensing or distribution. If you distribute or sublicense photographs, pass along these credit requirements.</p><p>This permission has no expiration and is irrevocable while you comply with its conditions, subject to any separate terms expressly agreed for particular photographs. You must be authorized to access the photograph. This permission does not let you bypass a private gallery, use another person’s account, or disclose private credentials or share codes. Copyright ownership remains with the respective rights holder; this is a permission to use the photograph, not a transfer of ownership.</p></section>
        <section><h2>Other people’s rights</h2><p>I can grant only rights that I control. This permission does not grant anyone’s privacy, publicity, trademark, or other third-party rights, or imply that a person shown endorses your use. You are responsible for obtaining any additional permissions your intended use requires.</p><p>Video, music, third-party material, and software have their own rights and licenses; the photograph permission above does not license them. Uses allowed by law, including applicable fair-use rights, are unaffected. Contact <SupportEmail subject="Photo use question" /> if you need help identifying a photograph or its rights holder.</p></section>
        <section><h2>Gallery and account access</h2><p>Use only accounts and private galleries you are authorized to access. Keep credentials and private sharing links secure. Do not bypass access controls, interfere with the site, send abusive or unlawful content, or use automated downloads in a way that disrupts service. Access may be limited to protect the site, the people depicted, or other users.</p><p>Gallery availability can change. Save any copies you are permitted to retain while access is available. Ask about delivery or archive availability if you need a file later; the website is not a promise of permanent storage.</p></section>
        <section><h2>Prints and photography inquiries</h2><p>Print-order information, shipping, returns, and support are described in <Link to="/print-policy">Print Orders & Returns</Link> and the applicable checkout terms. Sending an inquiry does not by itself reserve a session or establish a booking, price, deposit, or cancellation charge. Any service details must be agreed directly.</p></section>
        <section><h2>Photo concerns and removal requests</h2><p>If you appear in a photograph and have a privacy concern, or believe material on this site infringes your rights, contact <SupportEmail subject="Photograph concern or removal request" />. Include the page link, enough information to identify the photograph, and a description of your concern. I will review the request and may ask for clarification. You do not need an account to contact me.</p></section>
        <section><h2>Availability, changes, and your rights</h2><p>I aim to keep the site accurate and usable, but features may be interrupted, corrected, or changed. Screens and print materials may render color and cropping differently; this does not remove rights relating to faulty or incorrectly supplied products. These terms do not exclude consumer rights or responsibilities that cannot legally be excluded.</p><p>September 17, 2026 update: personal use remains credit-free; commercial use under this version requires credit to Ian Truong. Changes will be dated on this page. A later update does not retroactively change a completed order or a permission already granted for an earlier use. Contact me first about a problem so I can try to resolve it.</p></section>
    </LegalPage>
}
